[package]
name = "bottles-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-fs.workspace = true
async-trait.workspace = true
next-config.workspace = true
next-proto.workspace = true
fvs-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
directories.workspace = true
flate2.workspace = true
futures-core.workspace = true
futures-lite.workspace = true
futures-util.workspace = true
tar.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
regdiff-rs.workspace = true
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }
