[package]
name = "bottles-core"
description = "The application core for managing Bottles Next Wine and Proton environments."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/bottlesdevs/next-core/"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]

[features]
default = ["fvs"]
fvs = ["dep:blocking", "dep:fvs-rs", "dep:regdiff-rs"]

[dependencies]
async-fs.workspace = true
async-compression.workspace = true
async-io.workspace = true
async-process.workspace = true
async-trait.workspace = true
blocking = { workspace = true, optional = true }
download-manager.workspace = true
http-client = { workspace = true, features = ["reqwest"] }
next-config.workspace = true
next-proto.workspace = true
fvs-rs = { workspace = true, optional = true }
notify.workspace = true
keyvalues-parser.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio = { workspace = true, features = ["sync"] }
directories.workspace = true
futures-core.workspace = true
futures-lite.workspace = true
futures-util.workspace = true
smol-tar.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["rt"] }
regdiff-rs = { workspace = true, optional = true }
semver.workspace = true
strum.workspace = true
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v5"] }
keyring = "4.1.6"
egs-api = "0.14.0"
prost-wkt-types = "0.7.1"

[dev-dependencies]
async-executor.workspace = true
http.workspace = true
tokio = { workspace = true, features = ["net", "rt", "time"] }
