[package]
name = "bottles-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
prost = { workspace = true }
reqwest = "0.12"
tokio-util = { version = "0.7", features = ["rt"] }
url = "2.5.4"

[build-dependencies]
tonic-build = "0.12.3"
