[package]
name = "bottles-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
tracing = "0.1.41"
tonic = "0.12.3"
tokio = { version = "1.28.2", features = ["full"] }
prost = "0.13.4"

[build-dependencies]
tonic-build = "0.12.3"

[dev-dependencies]
tracing-subscriber = "0.3.19"
