[package]
name = "bottles-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-fs.workspace = true
async-compression.workspace = true
async-io.workspace = true
async-process.workspace = true
async-trait.workspace = true
blocking.workspace = true
next-config.workspace = true
next-proto.workspace = true
fvs-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio = { workspace = true, features = ["sync"] }
directories.workspace = true
futures-core.workspace = true
futures-lite.workspace = true
futures-util.workspace = true
smol-tar.workspace = true
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["rt"] }
regdiff-rs.workspace = true
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["net", "rt", "time"] }
