[package]
name = "bottles-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
tracing = "0.1.41"
unix-named-pipe = "0.2.0"

[dev-dependencies]
bottles-core = { path = "." }
tracing-subscriber = "0.3.19"
